version: 2
jobs:
    build:
        working_directory: ~/lemontech
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: echo "hello world"
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
